#!/usr/bin/env ruby

# Sample SpecTcl main program for testing GUI

require 'tk'
top = TkRoot.new { title "untitled test" }


# Interface generated by SpecTcl (Ruby enabled) version 1.1
# File: untitled.ui
# For use with Tk8.1 or later, using the grid geometry manager.

def untitled_ui (root) 

	# Widget creation.

	frame_2 = TkFrame.new (root
	)
	frame_1 = TkFrame.new (root
	)
	menubutton_1 = TkMenubutton.new (root,
		'text' => 'File'
	)
	menubutton_3 = TkMenubutton.new (root,
		'text' => 'Edit'
	)
	menubutton_2 = TkMenubutton.new (root,
		'text' => 'Help'
	)
	button_1 = TkButton.new (root,
		'text' => 'A Ruby Button'
	)
	button_2 = TkButton.new (root,
		'text' => 'Try-It!'
	)
	text_1 = TkText.new (root,
		'height' => '1',
		'width' => '1'
	)
	scrollbar_1 = TkScrollbar.new (root
	)
	scrollbar_2 = TkScrollbar.new (root,
		'orient' => 'horizontal'
	)

	# widget commands

	button_1.configure(
		'command' => proc {print "The Ruby Button was pressed.\n"}
	)

	# Geometry management

	frame_2.grid(
		'in' => root,
		'column' => 1,
		'row' => 1,
		'columnspan' => '3',
		'sticky' => 'w'
	)
	frame_1.grid(
		'in' => root,
		'column' => 1,
		'row' => 3,
		'columnspan' => '3',
		'sticky' => 'nesw'
	)
	menubutton_1.grid(
		'in' => frame_2,
		'column' => 1,
		'row' => 1
	)
	menubutton_3.grid(
		'in' => frame_2,
		'column' => 2,
		'row' => 1
	)
	menubutton_2.grid(
		'in' => frame_2,
		'column' => 4,
		'row' => 1
	)
	button_1.grid(
		'in' => root,
		'column' => 1,
		'row' => 2
	)
	button_2.grid(
		'in' => root,
		'column' => 2,
		'row' => 2
	)
	text_1.grid(
		'in' => frame_1,
		'column' => 1,
		'row' => 1,
		'sticky' => 'nesw'
	)
	scrollbar_1.grid(
		'in' => frame_1,
		'column' => 2,
		'row' => 1,
		'sticky' => 'ns'
	)
	scrollbar_2.grid(
		'in' => frame_1,
		'column' => 1,
		'row' => 2,
		'sticky' => 'ew'
	)

	# Resize behavior management.

	# Container frame_2 (rows).
	TkGrid.rowconfigure(frame_2, 1, 'weight'  => 0, 'minsize'  => 30)

	# Container frame_2 (columns).
	TkGrid.columnconfigure(frame_2, 1, 'weight' => 0, 'minsize' => 30)
	TkGrid.columnconfigure(frame_2, 2, 'weight' => 0, 'minsize' => 30)
	TkGrid.columnconfigure(frame_2, 3, 'weight' => 1, 'minsize' => 124)
	TkGrid.columnconfigure(frame_2, 4, 'weight' => 0, 'minsize' => 33)

	# Container root (rows).
	TkGrid.rowconfigure(root, 1, 'weight'  => 0, 'minsize'  => 30)
	TkGrid.rowconfigure(root, 2, 'weight'  => 0, 'minsize'  => 30)
	TkGrid.rowconfigure(root, 3, 'weight'  => 0, 'minsize'  => 30)

	# Container root (columns).
	TkGrid.columnconfigure(root, 1, 'weight' => 0, 'minsize' => 30)
	TkGrid.columnconfigure(root, 2, 'weight' => 0, 'minsize' => 30)
	TkGrid.columnconfigure(root, 3, 'weight' => 0, 'minsize' => 18)

	# Container frame_1 (rows).
	TkGrid.rowconfigure(frame_1, 1, 'weight'  => 1, 'minsize'  => 30)
	TkGrid.rowconfigure(frame_1, 2, 'weight'  => 0, 'minsize'  => 30)

	# Container frame_1 (columns).
	TkGrid.columnconfigure(frame_1, 1, 'weight' => 1, 'minsize' => 30)
	TkGrid.columnconfigure(frame_1, 2, 'weight' => 0, 'minsize' => 30)

	# Additional interface code.

	# End additional interface code.
end # untitled_ui

untitled_ui top
Tk.mainloop


